---
- name: Install OCS Agent
  hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Update Cache
      apt:
        update_cache: yes
    - name: Install Dependencies
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - libmodule-install-perl 
          - dmidecode 
          - libxml-simple-perl 
          - libcompress-zlib-perl
          - libnet-ip-perl
          - libwww-perl
          - libdigest-md5-perl
          - libdata-uuid-perl
          - libcrypt-ssleay-perl
          - libnet-snmp-perl
          - libproc-pid-file-perl
          - libproc-daemon-perl
          - net-tools
          - libsys-syslog-perl
          - pciutils
          - smartmontools
          - read-edid
          - nmap
  tasks:
    - name: Download OCS Unix Agent
      shell: wget -O /home/OCS-Agent.tar.gz https://github.com/OCSInventory-NG/UnixAgent/releases/download/v2.4.2/Ocsinventory-Unix-Agent-2.4.2.tar.gz
