---
- name: Install OCS Agent
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Install Dependencies
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - libmodule-install-perl 
          - dmidecode 
          - libxml-simple-perl 
          - libcompress-zlib-perl
          - libnet-ip-perl
          - libwww-perl
          - libdigest-md5-perl
          - libdata-uuid-perl
          - libcrypt-ssleay-perl
          - libnet-snmp-perl
          - libproc-pid-file-perl
          - libproc-daemon-perl
          - net-tools
          - libsys-syslog-perl
          - pciutils
          - smartmontools
          - read-edid
          - nmap
          - linet-netmask-perl
